name: Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  security-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: Run security tests
        run: make secure
