name: Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hofund:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Run security tests
        run: make secure
